apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: hbaf4ow58-nodejs 
  janus-idp.io/tekton: hbaf4ow58-nodejs
  backstage.io/kubernetes-id: hbaf4ow58-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: hbaf4ow58-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml