apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hbaf4ow58-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hbaf4ow58-nodejs 
  name: hbaf4ow58-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: hbaf4ow58-nodejs 
